apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nats-kv-demo-app
  annotations:
    version: v0.0.1
    description: "An application with a provider and component built for extending wasmCloud with nats-kv capabilities"
spec:
  components:
    - name: nats-kv-component
      type: component
      properties:
        image: file://./component/build/nats-kv_component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: nats-kv
            namespace: mattilsynet
            package: map-kv
            interfaces: [key-value]
            target_config:
              - name: nats-kv
                properties:
                  bucket: "managed-environment"
                  url: "nats://localhost:4222"
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
    - name: nats-kv
      type: capability
      properties:
        image: file://./build/map-nats-kv.par.gz
      traits:
        - type: link
          properties:
            target: nats-kv-component
            namespace: mattilsynet
            package: map-kv
            interfaces: [key-value-watcher]
            source_config:
              - name: nats-kv
                properties:
                  bucket: "test-bucket"
                  url: "nats://localhost:4222"
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: spreadscalar
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats-kv-component
            namespace: mattilsynet
            package: map-kv
            interfaces: [handler]
            source_config:
              - name: map-command-api-subject
                properties:
                  subscriptions: map.test
