name: build_push
on:
  push:
    tags:
      - 'v*'

jobs:
  wash-build:
    runs-on: ubuntu-latest
    env:
      providername: map-nats-kv
    permissions:
      contents: 'write'
      packages: 'write'
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      - name: install tinygo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.33.0'
          install-binaryen: 'false'
      - name: install wash tools
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-tools@1.225.0, wash-cli
      - name: install wit-bindgen-wrpc
        shell: bash
        run: |
          curl -LO https://github.com/bytecodealliance/wrpc/releases/download/v0.14.0/wit-bindgen-wrpc-x86_64-unknown-linux-musl;
          mv wit-bindgen-wrpc-x86_64-unknown-linux-musl wit-bindgen-wrpc
          chmod +x wit-bindgen-wrpc
          install -m 755 wit-bindgen-wrpc /usr/local/bin/
      - name: generate go files, provider
        shell: bash
        run: |
          go generate ./...
      - name: generate go files, component
        shell: bash
        run: |
          go get github.com/bytecodealliance/wasm-tools-go
          go generate ./...
        working-directory: component
      - name: validate-yaml
        shell: bash
        run: |
          [[ ! -f wadm.yaml ]] || wash app validate wadm.yaml
          [[ ! -f local.wadm.yaml ]] || wash app validate local.wadm.yaml
      - name: wash build provider
        shell: bash
        run: |
          wash build
      - name: wash build test-component
        shell: bash
        run: |
          wash build
        working-directory: component
      - name: test provider load
        shell: bash
        run: |
          set -xe
          wash up &
          WASH_PID=$!
          sleep 4;
          wash app deploy local.wadm.yaml;
          TRIES=0
          while [[ $(wash get inventory --output=json | jq '.inventories[0].providers | length') -eq 0 ]] ; do
            if [[ $TRIES -gt 10 ]]; then
              echo "❌ failed to find provider in inventory output after deploying example manifest";
              exit -1;
            fi
            TRIES=$((TRIES+1));
            sleep 1;
          done;
          echo "✅ successfully started at least one provider";
          wash app delete local.wadm.yaml;
          kill $WASH_PID;
          exit 0;
      - name: Setup registry
        env:
          WASH_REG_USER: ${{ github.actor }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cat << EOF > package_config.toml
          [namespace_registries]
          mattilsynet = "ghcr.io"

          [registry."ghcr.io".oci]
          auth = { username = "${WASH_REG_USER}", password = "${WASH_REG_PASSWORD}"}
          EOF
          echo "WASH_PACKAGE_CONFIG_FILE=$(realpath package_config.toml)" >> $GITHUB_ENV
      - name: publish package to github repository
        env:
          WASH_REG_USER: ${{ github.actor }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          wash push ghcr.io/${{ github.repository }}:${{ github.ref_name }} ${{ env.providername }}.par.gz --annotation org.opencontainers.image.source=${{github.server_url}}/${{ github.repository }}
        working-directory: build
      - name: Create tar.gz
        run: |
          tar -czf ${{ env.providername }}.tar.gz ./build/${{ env.providername }}.par.gz
      - name: build wit
        run: wash wit build
      - name: publish wit
        run: wash wit publish *.wasm
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Tag that triggered the workflow
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.providername }}.tar.gz # Path to your file
          asset_name: ${{ env.providername }}
          asset_content_type: application/gzip

#TODO: run wash up, wash apply and check output for success messages

